# Generated by Django 5.1 on 2024-08-23 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'Категорію', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Назва'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Зображення')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Ціна')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Знижка в %')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('rootstock', models.CharField(help_text='Підвой', max_length=200)),
                ('ripening_period', models.CharField(help_text='Терміни дозрівання', max_length=200)),
                ('fruit_weight', models.DecimalField(decimal_places=2, help_text='Маса плодів у грамах', max_digits=5)),
                ('pollinators', models.CharField(blank=True, help_text='Опилювачі', max_length=200, null=True)),
                ('frost_resistance', models.CharField(blank=True, help_text='Морозостійкість', max_length=200, null=True)),
                ('disease_resistance', models.CharField(blank=True, help_text='Стійкість до захворювань', max_length=200, null=True)),
                ('transportability', models.CharField(blank=True, help_text='Транспортабельність', max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Саджанець',
                'verbose_name_plural': 'Саджанці',
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
    ]
