# Generated by Django 5.1 on 2025-02-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='disease_resistance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Стійкість до захворювань'),
        ),
        migrations.AlterField(
            model_name='products',
            name='frost_resistance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Морозостійкість'),
        ),
        migrations.AlterField(
            model_name='products',
            name='fruit_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Маса плодів у грамах'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pollinators',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Опилювачі'),
        ),
        migrations.AlterField(
            model_name='products',
            name='ripening_period',
            field=models.CharField(max_length=200, verbose_name='Терміни дозрівання'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rootstock',
            field=models.CharField(max_length=200, verbose_name='Підвой'),
        ),
        migrations.AlterField(
            model_name='products',
            name='transportability',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Транспортабельність'),
        ),
    ]
